simonyiszk/mabe

src/components/layouts/PageLayout.tsx
src/pages/_app.tsx
src/pages/index.tsx

Add page layout #31

---

src/components/events/EventCard.tsx
src/components/ui/Event.tsx
tailwind.config.js

Closes #9
A kép reszponzív kezelését még lehet másként jobb lenne kezelni (kis képernyőn levágni a szélét), de egyelőre szerintem jó lesz így.

Add event card component #9

---

next.config.js
src/components/events/EventCard.tsx
src/components/header/Header.tsx
src/components/layouts/EventsPageLayout.tsx
src/mock.ts
src/pages/esemenyek.tsx
tailwind.config.js

Add events page layout #10

---

src/components/gallery/GalleryCard.tsx
tailwind.config.js

Task/6 - Galéria kártya komponens

---

src/components/header/HamburgerMenu.tsx
src/components/header/Header.tsx

Task 35 fix hamburger menu and header

---

src/components/header/Logo.tsx

fix logo position

---

src/components/header/HamburgerMenu.tsx
src/components/header/Header.tsx
src/components/layouts/PageLayout.tsx
src/pages/esemenyek/index.tsx
src/styles.css
tailwind.config.js

Add custom fonts

---

src/components/layouts/GalleryPageLayout.tsx
src/components/layouts/SelectedGalleryPageLayout.tsx
src/mock.ts
src/pages/galeria/[id].tsx
src/pages/galeria/index.tsx

Task/7 - Galéria nézet

---

src/styles.css

lehetséges megoldás erre?  
`... find a way to crop at the middle on small screens` #54 
closes #55

bg cover repeat fix

---

src/components/layouts/AnyPageLayout.tsx
src/components/members/MemberCard.tsx
src/pages/tagok/index.tsx
tailwind.config.js

bármiféle helpet elfogadok, mert nem áll nekem ez össze

add members page and member card

---

src/pages/galeria/index.tsx

add roboto slab to title

---

src/components/ui/Partner.tsx
src/mock.ts
src/pages/partnerek/index.tsx

A partnerek oldal mellett a partner kártyákon opcionális lett:
- email cím
- telefonszám
- cím

Task/19 - Partnerek oldal

---

src/components/members/MemberCard.tsx

Update member card styles

---

src/components/footer/Footer.tsx
src/components/footer/icons/InstagramIcon.tsx

Fix and update footer

---

src/@types/generated/contentful.d.ts

dotenvet hozzáadtam dev dependencyként esetleges későbbi generáláshoz

remove contentful interface optionals

---

src/components/header/Logo.tsx

add cursor-pointer

---

src/@types/generated/contentful.d.ts
src/components/documents/DocumentCard.tsx
src/components/header/HeaderLinkList.tsx
src/pages/dokumentumok/index.tsx
src/utils/contentful.ts

Dokumentumok oldal

---

src/components/header/HeaderLinkList.tsx
src/pages/csatlakozz/index.tsx
src/pages/index.tsx
src/pages/sitemap.xml.ts
src/utils/contentful.ts

csatlakozz oldal

---

src/components/news/NewsCard.tsx

fix truncation

---

src/components/header/HeaderLinkList.tsx
src/pages/csapatunk/index.tsx
src/pages/sitemap.xml.ts

rename tagok page to csapatunk

---

src/components/header/HeaderLinkList.tsx
src/components/news/NewsAuthor.tsx
src/components/news/NewsCard.tsx
src/pages/blog/[slug].tsx
src/pages/blog/index.tsx
src/pages/sitemap.xml.ts

rename hirek page to blog

---

src/@types/generated/contentful.d.ts

changes were also made on contentful
closes #148

make address and email optional

---

src/components/header/HeaderLinkList.tsx

reorder menu links

---

src/components/events/EventCard.tsx
src/components/footer/SocialIcon.tsx
src/components/gallery/GalleryCard.tsx
src/components/header/Logo.tsx
src/components/homepage/BottomSection.tsx
src/components/homepage/Goals.tsx
src/components/homepage/LinkIconsSection.tsx
src/components/homepage/MiddleSection.tsx
src/components/homepage/PartnersCard.tsx
src/components/members/MemberCard.tsx
src/components/news/NewsAuthor.tsx
src/components/news/NewsCard.tsx
src/components/partners/Partner.tsx
src/pages/blog/[slug].tsx
src/pages/esemenyek/[slug].tsx
src/pages/galeria/[slug].tsx
src/utils/RenderOptions.tsx

changes usage of old `next/legacy/image` to `next/image`

migrate from legacy image

---

CHANGELOG.md
package.json
src/components/header/HeaderLinkList.tsx

173 remove documents link from header
